### ISSUE TITLE
Menu popup color should be changed (for mobile)

### ISSUE THREAD

**Issue by aliahmed102** [pixprocoder/pixprocoder#11]
The color dose not match the theme of the website

**Comment by pixprocoder** [comment]
Okay sure I am working on it

**Comment by pixprocoder** [comment]
@aliahmed102 you can check it  out  now
[
![image](https://github.com/user-attachments/assets/deaf24f8-7edc-46c3-9ea5-b6db01ec7831)
](url)

**Comment by aliahmed102** [comment]
> @aliahmed102 you can check it out now [ ![image](https://private-user-images.githubusercontent.com/89704576/351937968-deaf24f8-7edc-46c3-9ea5-b6db01ec7831.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NzU1MTMsIm5iZiI6MTcyMTg3NTIxMywicGF0aCI6Ii84OTcwNDU3Ni8zNTE5Mzc5NjgtZGVhZjI0ZjgtN2VkYy00NmMzLTllYTUtYjZkYjAxZWM3ODMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAyNDAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNjY5ZGQ4N2Q4YWViZmQwZTAwY2E0Nzc4YWQ2MTgwN2IxN2Q5ZmZlNmE1YjgwYTQyYTAxZTVmMzE3MThhMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KrjO-qnwqvWXe7u1_A5NfQEInY6WETK5NX9diwRhCj4) ](url)

well done
