### ISSUE TITLE
Contact  Page Problem

### ISSUE THREAD

**Issue by aliahmed102** [pixprocoder/pixprocoder#13]
after submiting form it won't reset form 
![image](https://github.com/user-attachments/assets/3692ade8-ecad-4a9a-8418-0cf071b1d002)

and I think the problem with api endpoint data won't pass  correctly
fix this

**Comment by pixprocoder** [comment]
OK I am Looking at this :)

**Comment by pixprocoder** [comment]
@aliahmed102 Thanks for the issue I have fixed already
