### ISSUE TITLE
Add Loading spinner 

### ISSUE THREAD

**Issue by pixprocoder** [pixprocoder/pixprocoder#15]
![image](https://github.com/user-attachments/assets/2c46be40-7382-4c63-bb55-b79424030525)
insted of this add nice spinner

**Comment by aliahmed102** [comment]
Ok

**Comment by timothyJasonC** [comment]
Hi, I'm Timothy.

I noticed that you had a little problem with your navbar because it didn't look quite right. So, I fixed it using Framer, and now it looks much better, like the sheet component from Shadcn. Please accept my pull request if you find it helpful.

**Comment by pixprocoder** [comment]
spinner added
