### ISSUE TITLE
Fix when mobile menu item clicked the menu also close

### ISSUE THREAD

**Issue by pixprocoder** [pixprocoder/pixprocoder#20]
on mobile menu the link such as portfolio, services when clicked the link goes to the page but the menu still open. need to be fixed

**Comment by timothyJasonC** [comment]
hi, I forgot to check that feature, I have fixed it so that when the navigation items is clicked it will close the sidebar tab and redirect to the specified link, you review it on my pull request

**Comment by pixprocoder** [comment]
@timothyJasonC Hi I checked everything works fine but the signup button doesn't could you take a look please and make another PR

**Comment by timothyJasonC** [comment]
@pixprocoder I already make a PR to fix that bug can you check it and add your review

**Comment by pixprocoder** [comment]
@timothyJasonC Now it's perfect! 👍
