### ISSUE TITLE
Fix hamburger menu links for mobile 

### ISSUE THREAD

**Issue by pixprocoder** [pixprocoder/pixprocoder#9]
when click the link it don't collapse 
![Screenshot_20240724-054134_Brave](https://github.com/user-attachments/assets/b34a70fe-9f08-4dbb-8ff6-4513e8326070)
and make the colors fix

**Comment by aliahmed102** [comment]
Yes it would be nice

**Comment by pixprocoder** [comment]
> Yes it would be nice

Now you can check when I click line the menu also close
